/*<?php
$css = $js = '/'.'** OPENLAYERS ADAPTATION'.PHP_EOL.
' * © Dominique Cavailhez 2017'.PHP_EOL.
' * https://github.com/Dominique92/MyOl'.PHP_EOL.
' * Based on https://openlayers.org'.PHP_EOL.
' *'.PHP_EOL.
' * This file is generated by build.php from the src/'.'* sources'.PHP_EOL.
' * Please dont modify it. Modify src/'.'* & rebuild it !'.PHP_EOL.
' *'.'/'.PHP_EOL.PHP_EOL.PHP_EOL;

$css .= get ('myol.css');
$css .= get ('layerSwitcher.css');
file_put_contents ('../myol.css', $css);

$js .= get ('misc.js');
$js .= get ('tileLayers.js');
$js .= get ('layerSwitcher.js');
$js .= get ('myol.js');
file_put_contents ('../myol.js', $js);

function get ($file) {
	$text = file_get_contents ('../src/'.$file);
	$texts = explode ('/'.'*--*'.'/', $text);

	return isset ($texts[1]) ? $texts[1] : $text;
}
?>*/